name: TEST

on: [ push, pull_request ]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: pnpm install

      - name: Run tests
        run: pnpm test
